allowBuilds:
  core-js: true
  core-js-pure: true
  es5-ext: true
  gatsby: true
  gatsby-cli: true
  lmdb: true
  msgpackr-extract: true
  puppeteer: true
  sharp: true
nodeLinker: hoisted
overrides:
  sanitize-html: 2.17.7
