allowBuilds:
  core-js: true
  core-js-pure: true
  es5-ext: true
  gatsby: true
  gatsby-cli: true
  git-win: false
  lmdb: true
  msgpackr-extract: true
  puppeteer: true
  sharp: true
nodeLinker: hoisted
overrides:
  "@babel/plugin-transform-modules-systemjs@7.23.3": 7.29.4
  "@types/reach__router>@types/react": 19.2.18
  "ajv@6.12.6": 6.14.0
  "ajv@8.17.1": 8.18.0
  "flatted@3.2.9": 3.4.2
  "immutable@3.7.6": 4.3.9
  "js-yaml@4.1.0": 4.3.1
  "joi@17.13.3": 17.13.4
  "lodash@4.17.21": 4.18.1
  "lodash.template@4.5.0": 4.18.1
  "minimatch@3.1.2": 3.1.4
  "multer@2.0.2": 2.2.0
  "on-headers@1.0.2": 1.1.0
  "path-to-regexp@0.1.10": 0.1.13
  "path-to-regexp@0.1.12": 0.1.13
  "picomatch@2.3.1": 2.3.2
  "puppeteer@19.11.1": 25.7.0
  "qs@6.13.0": 6.15.3
  "serialize-javascript@5.0.1": 7.1.0
  "serialize-javascript@6.0.2": 7.1.0
  "sharp@0.32.6": 0.35.3
  "svgo@2.8.0": 2.8.3
  "tmp@0.0.33": 0.2.7
  "tmp@0.2.1": 0.2.7
  "ws@8.11.0": 8.21.3
  "ws@8.13.0": 8.21.3
  "yaml@1.10.2": 1.10.3
  sanitize-html: 2.17.7
  shell-quote: 1.10.0
  "tar-fs@2.1.1": 2.1.4
  "tar-fs@3.0.4": 3.1.1
peerDependencyRules:
  allowedVersions:
    "@gatsbyjs/reach-router>react": "19"
    "@gatsbyjs/reach-router>react-dom": "19"
