allowBuilds:
  core-js: true
  core-js-pure: true
  es5-ext: true
  gatsby: true
  gatsby-cli: true
  git-win: false
  lmdb: true
  msgpackr-extract: true
  puppeteer: true
  sharp: true
nodeLinker: hoisted
overrides:
  "@types/reach__router>@types/react": 19.2.18
  "immutable@3.7.6": 4.3.9
  "minimatch@3.1.2": 3.1.4
  sanitize-html: 2.17.7
  shell-quote: 1.10.0
  "tar-fs@2.1.1": 2.1.4
  "tar-fs@3.0.4": 3.1.1
peerDependencyRules:
  allowedVersions:
    "@gatsbyjs/reach-router>react": "19"
    "@gatsbyjs/reach-router>react-dom": "19"
